[workspace]
members = [
    "types",
    "blocking",
    "async",
    "examples/command_loop",
    "examples/command_loop_async_std",
    "examples/event_printer",
    "examples/event_printer_tokio",
    "examples/hovered_window",
    "examples/hovered_window_futures_lite",
]
