[package]
name = "swayipc"
version = "1.1.2"
authors = ["Rex Hackbro <rex.hackbro@mailbox.org>"]
edition = "2018"
description = "A library for controlling sway through its IPC interface"
license = "MIT"
repository = "https://github.com/jaycefayne/swayipc-rs"
keywords = ["sway", "swaywm", "swayipc","ipc", "serde"]
readme = "README.md"

[dependencies]
byteorder = "1.3.2"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
failure = "0.1.6"
