[package]
name = "swayipc"
version = "2.3.1"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"
description = "A library for controlling sway through its IPC interface"
license = "MIT"
repository = "https://github.com/jaycefayne/swayipc-rs"
categories = ["asynchronous", "concurrency", "network-programming"]
keywords = ["sway", "swaywm", "swayipc","ipc", "async"]
readme = "README.md"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
failure = "0.1.6"
futures-core = { version = "0.3.1", optional = true }
async-std = { version = "1.4.0", optional = true }

[features]
default = []
async = ["async-std"]
event_stream = ["futures-core"]

[[example]]
name = "command_loop"
path = "examples/command_loop/src/main.rs"

[[example]]
name = "command_loop_async"
path = "examples/command_loop_async/src/main.rs"
required-features = ["async"]

[[example]]
name = "event_printer"
path = "examples/event_printer/src/main.rs"

[[example]]
name = "event_printer_async_event_stream"
path = "examples/event_printer_async_event_stream/src/main.rs"
required-features = ["async", "event_stream"]

[[example]]
name = "event_printer_async"
path = "examples/event_printer_async/src/main.rs"
required-features = ["async"]

[[example]]
name = "hovered_window"
path = "examples/hovered_window/src/main.rs"

[[example]]
name = "hovered_window_async"
path = "examples/hovered_window_async/src/main.rs"
required-features = ["async"]
