[package]
name = "swayipc"
version = "2.2.5"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"
description = "A library for controlling sway through its IPC interface"
license = "MIT"
repository = "https://github.com/jaycefayne/swayipc-rs"
keywords = ["sway", "swaywm", "swayipc","ipc", "async"]
readme = "README.md"

[dependencies]
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.44"
failure = "0.1.6"
async-std = { version = "1.3.0", optional = true }

[features]
default = []
async = ["async-std"]
