[package]
name = "swayipc-async"
version = "2.0.0-alpha.3"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"
description = "A library for controlling sway through its IPC interface"
license = "MIT"
repository = "https://github.com/jaycefayne/swayipc-rs"
categories = ["network-programming"]
keywords = ["sway", "swaywm", "swayipc","ipc", "async"]
readme = "README.md"

[dependencies]
swayipc-types = { version = "1.0.0-alpha.3", path = "../types" }
serde = "1.0.117"
serde_json = "1.0.60"
async-io  = "1.3.1"
futures-lite = "1.11.2"
