[package]
name = "command_loop_async_std"
version = "1.0.0"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"

[dependencies]
swayipc-async = { path = "../../async" }
async-std = { version = "1.10.0", features = ["attributes"]}
