[package]
name = "event_printer_async_event_stream"
version = "1.0.0"
authors = ["Jayce Fayne <jayce.fayne@mailbox.org>"]
edition = "2018"

[dependencies.swayipc]
path = "../../"
features = ["async", "event_stream"]
